create table if not exists book (
    id bigint generated by default as identity not null,
    isbn varchar(13) not null,
    publisher varchar(100) not null,
    title varchar(255) not null,
    author_id bigint,
    primary key (id)
);

create table if not exists author (
    id bigint generated by default as identity not null,
    firstname varchar(50) not null,
    lastname varchar(50) not null,
    primary key (id)
);